<?php 
 return array(
    'enter_order_status'=>array(
        '0'=>'未确认',
        '1'=>'已确认',
        '2'=>'已入库',
        '3'=>'已完成',
    ),
    'outer_order_status'=>array(
         '0'=>'未确认',
         '1'=>'已确认',
         '2'=>'已出库',
         '3'=>'已完成',
     ),
     'rectify_order_status'=>array(
         '0'=>'未确认',
         '1'=>'已确认',
         '2'=>'已调整',
         '3'=>'已完成',
     ),
     'purchase_order_status'=>array(
         '0'=>'未确认',
         '1'=>'已确认',
         '2'=>'已生成入库单',
         '3'=>'已完成',
     )
);
?>